[workspace]
authors = ["Mike Stebler <mstebler@ethz.ch>"]
channels = ["conda-forge"]
name = "ia_PoC_002"
platforms = ["win-64"]
version = "0.1.0"
license = "MIT"
license-file = "LICENSE"

[tasks]

[dependencies]
python = "3.12.*"
bioio = ">=3.3.0,<4"
scikit-image = ">=0.24"
scipy = ">=1.13"
matplotlib = ">=3.9"

[pypi-dependencies]
bioio-czi = ">=2.7.0, <3"
